#!/bin/bash
# action-log.sh — Append one line per tool use to ACTION-LOG.md
# Used by PostToolUse and PostToolUseFailure hooks (matcher: "")
# Input: JSON on stdin with tool_name, tool_input, and tool_response or error

INPUT=$(cat)
TOOL_NAME=$(echo "$INPUT" | jq -r '.tool_name // "unknown"')
HOOK_EVENT=$(echo "$INPUT" | jq -r '.hook_event_name // "PostToolUse"')
TIMESTAMP=$(date +%H:%M:%S)

LOG_FILE="ACTION-LOG.md"

# Create header if file doesn't exist or is empty
if [ ! -f "$LOG_FILE" ] || [ ! -s "$LOG_FILE" ]; then
  echo "# Action Log" > "$LOG_FILE"
  echo "> Auto-generated by hooks. One line per tool use. Never edit manually." >> "$LOG_FILE"
  echo "" >> "$LOG_FILE"
fi

# Determine PASS/FAIL
if [ "$HOOK_EVENT" = "PostToolUseFailure" ]; then
  STATUS="FAIL"
  ERROR_LINE=$(echo "$INPUT" | jq -r '.error // "" | split("\n")[0] // ""' | head -c 120)
  DETAIL=" ($ERROR_LINE)"
else
  STATUS="PASS"
  DETAIL=""
fi

# Extract per-tool summary
case "$TOOL_NAME" in
  Bash)
    COMMAND=$(echo "$INPUT" | jq -r '.tool_input.command // ""' | head -c 120)
    SUMMARY="$COMMAND$DETAIL"
    ;;
  Read)
    FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // ""')
    SUMMARY="$FILE_PATH$DETAIL"
    ;;
  Edit)
    FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // ""')
    SUMMARY="$FILE_PATH$DETAIL"
    ;;
  Write)
    FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // ""')
    SUMMARY="$FILE_PATH$DETAIL"
    ;;
  Glob)
    PATTERN=$(echo "$INPUT" | jq -r '.tool_input.pattern // ""')
    SUMMARY="$PATTERN$DETAIL"
    ;;
  Grep)
    PATTERN=$(echo "$INPUT" | jq -r '.tool_input.pattern // ""')
    GREP_PATH=$(echo "$INPUT" | jq -r '.tool_input.path // "."')
    SUMMARY="/$PATTERN/ in $GREP_PATH$DETAIL"
    ;;
  Task)
    DESC=$(echo "$INPUT" | jq -r '.tool_input.description // ""')
    SUMMARY="$DESC$DETAIL"
    ;;
  *)
    SUMMARY="$TOOL_NAME$DETAIL"
    ;;
esac

echo "[$TIMESTAMP] $TOOL_NAME $STATUS — $SUMMARY" >> "$LOG_FILE"
exit 0
