services:
  api:
    build:
      context: ../../App/Server
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5000
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/swagger/index.html"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    
  newman:
    image: postman/newman:alpine
    depends_on:
      api:
        condition: service_healthy
    volumes:
      - ./:/etc/newman
      - ../../reports:/reports
    environment:
      APIURL: http://api:5000/api
      USERNAME: soloyolo
      EMAIL: soloyolo@mail.com
      PASSWORD: password123
      FOLDER: ${FOLDER}
    entrypoint: >
      sh -lc 'newman run /etc/newman/Conduit.postman_collection.json
      $${FOLDER:+--folder "$$FOLDER"} 
      --delay-request 25
      --reporters json
      --reporter-json-export /reports/newman-report.json
      --global-var "APIURL=$$APIURL" --global-var "USERNAME=$$USERNAME"
      --global-var "EMAIL=$$EMAIL" --global-var "PASSWORD=$$PASSWORD"'
