services:
  api:
    build:
      context: ../../App/Server
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:5000
      ConnectionStrings__SqliteConnection: "Data Source=/app/src/Server.Web/database.sqlite"
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/swagger/index.html"]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 30s
    
  newman:
    image: postman/newman:alpine
    depends_on:
      api:
        condition: service_healthy
    volumes:
      - ./:/etc/newman
      - ../../reports:/reports
    environment:
      - APIURL=http://api:5000/api
      - USERNAME=soloyolo
      - EMAIL=soloyolo@mail.com
      - PASSWORD=password123
    command: [
      "run", "/etc/newman/Conduit.postman_collection.json",
      "--folder", "${FOLDER}",
      "--delay-request", "25",
      "--reporters", "cli,json",
      "--reporter-json-export", "/reports/newman-report.json",
      "--global-var", "APIURL=http://api:5000/api",
      "--global-var", "USERNAME=soloyolo", 
      "--global-var", "EMAIL=soloyolo@mail.com",
      "--global-var", "PASSWORD=password123"
    ]
