// <auto-generated />
using Finbuckle.MultiTenant.Abstractions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Server.Infrastructure.Data;

#nullable disable

namespace Server.Infrastructure.Data.Migrations.TenantStore;

[DbContext(typeof(TenantStoreDbContext))]
partial class TenantStoreDbContextModelSnapshot : ModelSnapshot
{
  protected override void BuildModel(ModelBuilder modelBuilder)
  {
#pragma warning disable 612, 618
    modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

    modelBuilder.Entity("Finbuckle.MultiTenant.Abstractions.TenantInfo", b =>
    {
      b.Property<string>("Id")
        .HasMaxLength(64)
        .HasColumnType("TEXT");

      b.Property<string>("Identifier")
        .IsRequired()
        .HasMaxLength(450)
        .HasColumnType("TEXT");

      b.Property<string>("Name")
        .IsRequired()
        .HasMaxLength(256)
        .HasColumnType("TEXT");

      b.HasKey("Id");

      b.HasIndex("Identifier")
        .IsUnique();

      b.ToTable("TenantInfo");
    });
#pragma warning restore 612, 618
  }
}
